# Generated by Django 6.0.5 on 2026-06-10 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='difficulty',
            field=models.CharField(choices=[('easy', '🟢 簡單'), ('medium', '🟡 中等'), ('hard', '🔴 困難')], default='easy', max_length=10, verbose_name='難易度'),
        ),
    ]
