# Generated by Django 6.0.5 on 2026-06-10 19:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_question_difficulty'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(verbose_name='得分')),
                ('total_questions', models.IntegerField(verbose_name='總題數')),
                ('difficulty', models.CharField(choices=[('easy', '🟢 簡單'), ('medium', '🟡 中等'), ('hard', '🔴 困難')], default='easy', max_length=10, verbose_name='測驗難度')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='交卷時間')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='測驗者')),
            ],
        ),
    ]
