# Generated by Django 6.0.5 on 2026-06-10 19:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_wronganswer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wronganswer',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='choice',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='choice',
            name='text',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='difficulty',
            field=models.CharField(choices=[('easy', '🟢 簡單'), ('medium', '🟡 中等'), ('hard', '🔴 困難')], default='easy', max_length=10),
        ),
        migrations.AlterField(
            model_name='quizrecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='quizrecord',
            name='difficulty',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='quizrecord',
            name='score',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='quizrecord',
            name='total_questions',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='quizrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='wronganswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.question'),
        ),
        migrations.AlterField(
            model_name='wronganswer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
